### ISSUE TITLE
Some general questions about the UbiArt Framework/Rayman Legends logic.

### ISSUE THREAD

**Issue by GitLordv** [byvar/ubi-canvas#23]
1) Will there be an option in the near future to export Rayman Legends files - (_Mat Shader files_) [**.msh**, **.fxb**] or possibly [.tpl; .act] into a readable format?
Text or maybe Json?

2) TPL files (example: "common/camera/cameramodifier.tpl.ckd") seem to weigh very little, but what are they? A parameter file for a particular object template? 
If I replace it with another file "common/maze/cameramodifier.tpl.ckd", the game suddenly continues to run without problems, but with a different camera behavior (free camera on some levels). 
Why is this happening?

**Comment by byvar** [comment]
Hi!

1. Aside from .fxb (which are compiled HLSL shaders, unlike .msh which is a UbiArt material shader file), it is possible to log these files showing exactly what data is at every offset in the file. You can do so by enabling the "Serialization Log" option in the ubi-canvas Settings window, and loading a scene that uses them (or loading the file through the "Actor Tools" window).
It is also possible to log specific files without loading a scene, using the "Deserialize & log file" Game Tool (in a separate window named "Game Tools"). With the "Serialization Log" option active, enter a path like "world/common/playablecharacter/rayman/rayman.tpl" or "world/common/matshader/default.msh" and click the "Deserialize" button. As these are generic files, there is no need to specify a file type. (For .act files, you will need to specify File type = "Actor" and "Use file container = true")


2. TPL files are actor templates - you can see each actor as an instance of one of these templates. While each actor has its own instance-specific configuration, usually most settings are specified in its template, to avoid repeated data. Because you made every actor that used the normal cameramodifier template use the maze cameramodifier one, most cameramodifiers use a fundamentally different configuration, changing their behavior. I wouldn't advise swapping templates like this however, as this will easily cause crashes due to differences between components (and other things) between the instances and their templates.
For more information on this, it might be a good idea to check out the Wiki: [Terminology](https://github.com/byvar/ubi-canvas/wiki/Terminology) and [File types](https://github.com/byvar/ubi-canvas/wiki/File-types). It isn't much, but still provides some insight on the UbiArt Framework. :)
